# Generated by Django 5.0.11 on 2025-02-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscriptions_active_alter_subscriptions_premission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='premission',
            new_name='permissions',
        ),
    ]
